settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: olaris
  path: .
  commands:
    generate:
      status: true
    build:
      status: true
      dir: cmd/olaris
    run:
      status: true
      path: cmd/olaris
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
